version: 0.2

env:
  variables:
    SENTRY_ORG: 'usc-ict-ls'
    SENTRY_PROJECT: 'mentor-lrs'

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # workaround https://github.com/aws/aws-codebuild-docker-images/issues/490:
      - n 16
      - NODE_ENV=dev npm ci

  build:
    commands:
      - echo "todo add commands"
      # - npm run test:format
      # - npm run test:license
      # - npm run test:lint
      # - npm run test:types
      # - npm run test

artifacts:
  files:
    - '**/*'
  enable-symlinks: yes
